# Test your FastAPI endpoints

GET http://127.0.0.1:8000/movies/
Accept: application/json

###

POST http://127.0.0.1:8000/movies
Content-Type: application/json

{
  "title": "Batman Begins",
  "year": 2005,
  "director": "Christopher Nolan",
  "description": ""
}

###

GET http://127.0.0.1:8000/movies/14
Accept: application/json

###

DELETE http://127.0.0.1:8000/movies/14
Accept: application/json

###

GET http://127.0.0.1:8000/actors
Accept: application/json

###

GET http://127.0.0.1:8000/actors/2
Accept: application/json
###

POST http://127.0.0.1:8000/actors
Content-Type: application/json

{
  "name": "Bruce",
  "surname": "Willis"
}
###

DELETE http://127.0.0.1:8000/actors/2
Accept: application/json


###
POST http://127.0.0.1:8000/movies/2/actors
Content-Type: application/json

{
  "name": "Roy",
  "surname": "Scheider"
}


